### PR TITLE
:lipstick: add new theme "Chimera-nightsky"

### PR DESCRIPTION
**Pull request by SindreKjelsrud**

### CODE REVIEW

**Comment by SindreKjelsrud** [comment]
Screenshot of Chimera-nightsky:

chimera-nightsky

**Review by MarkusJohansen — DISMISSED** [review]
The theme looks nice and also very professional! However the link colors creates to little contrast between the background and the links, and this has to be adressed to make the theme *accesible*. I also think that the focus color doesnt quite fit the palette, which is why I would tweak this too. Experiment with different colors and find something that feels right 👍🏼  I added some suggestions, but feel free to try something else 💯 

```
$Chimera-link: hsl(210, 90%, 60%);
$Chimera-focus: hsl(175, 70%, 50%);
```

**Comment by MarkusJohansen** [comment]
We wont need the image in the readme as those have been purged to keep the package smaller.

**Comment by MarkusJohansen** [comment]
Have you tried accesibility testing using google lighthouse? If thats the case, how did the accesibility score look? It should be pretty good to avoid contributing to making this issue even bigger: #104

**Comment by SindreKjelsrud** [comment]
After updating some colors the theme went from a 95 score to a 100 score in accessibility using google lighthouse locally.

Screenshot from 2024-01-23 17-58-35

**Review by SindreKjelsrud — COMMENTED** [review]
Requested changes have been addressed.

**Pull request merged**
